### ISSUE TITLE
rgb2hex returns rgba(186,100,100,1) -> #ba.1ee58469ee663.dcda7517a44c63.dcda7517a44c

### ISSUE THREAD

**Issue by BradHarris** [WickyNilliams/pure-color#8]
It looks like the decimal place is not being rounded off when converting back to hex from rgb.

**Comment by WickyNilliams** [comment]
What decimal place? Just tested in the console and I got:

``` bash
> var rgb2hex = require("./convert/rgb2hex")
undefined
> rgb2hex([186,100,100,1])
'#ba6464'
```

Are you sure that was your input?

**Comment by WickyNilliams** [comment]
Test for yourself here: https://tonicdev.com/npm/pure-color

``` js
var rgb2hex = require("pure-color/convert/rgb2hex");
rgb2hex([186,100,100,1])
```

**Comment by BradHarris** [comment]
You know what, it looks like my numbers earlier on have decimals... I'll double check some other things and then I'll close this issue if this is the case.

**Comment by BradHarris** [comment]
Yup, my mistake! Somehow one of my functions is introducing decimals :(

**Comment by WickyNilliams** [comment]
No worries :) 

I wonder if `rgb2hex` should handle this anyway. Converting between color spaces you may get decimal values, so it should probably be handled i guess?

**Comment by BradHarris** [comment]
Maybe. Could just introduce a floor function to trim decimals optionally. I'm trying to pinpoint where the decimal is being introduced in my code. I'm modifying someone's color picker library which uses your library.

**Comment by WickyNilliams** [comment]
Are you modifying my color picker? It's the only one dependent on this lib AFAIK :D

**Comment by BradHarris** [comment]
YES! It is yours!

**Comment by BradHarris** [comment]
I've gone through 3 different color picker libraries now and yours is nice and simple and I can easily extend it to give me the functionality I need.

**Comment by WickyNilliams** [comment]
Haha! I built the color picker because all the existing ones were too complex, or had bugs around extreme saturation values. Then I wasn't happy with the existing color conversion/parsing libs (also too heavyweight), so I built this lib specifically for the purpose.

Any reason you're modifying the color picker? Or are you extending it through composition? The color picker was designed to be easily extensible :) but if there's a feature missing I'd be open to adding it

**Comment by BradHarris** [comment]
Actually there was one problems I encountered while using it but I could make issues in that repo if you would like. My project requires react/addons when I require your color picker it requires react and that causes problems. I've tried to use a few libraries that do this and I've had to either drop them entirely, form them and fix the issue, or just copy their source if there were other things I wanted to change.

**Comment by WickyNilliams** [comment]
Yes please raise an issue there. I am aware of this. It's because I list react as a dependency instead of a peer dependency. I broke my app in production because of this :scream:

I've been meaning to fix anyway, this is good encouragement to do so :)

**Comment by WickyNilliams** [comment]
This is now fixed

**Comment by BradHarris** [comment]
Yeah it is! Thanks!
